name: Ruby

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.7'
          - '3.2'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Bundle
      run: |
        bundle config set --local without development
        bundle install
    - name: Test
      run: |
        bundle exec rake rubocop
        bundle exec rake spec

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    name: Deploy
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
    - name: Release gem
      run: |
        mkdir -p $HOME/.gem
        printf -- "---\n:github: Bearer ${{secrets.GITHUB_TOKEN}}\n" > $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        gem build
        gem push --key github --host https://rubygems.pkg.github.com/${{github.repository_owner}} *.gem
